[Feature] : Ourservice component
primathonacademy/april-batch-live-project pull request #24
Opened 2024-02-28 10:39 UTC by Himanshushakyaa

## Description

-   [Ticket Link](#) (if any)
- create ourservice components with fully responsive and animated

## UI screenshot or Video

https://github.com/primathonacademy/april-batch-live-project/assets/131392846/8191cd4e-e1aa-4249-ac6e-2a3876975fd1

-  

---

## Checklist - All needs to be ticked before sending PR for review:

### General:

-   [x] **PR Size :** Confirming PR size < 20 files or pre-approved if > 20 files.
-   [x] **Self Review :** Confirming I have self-reviewed my PR
-   [x] **Peers Review :** - [ ] @Dev 1
-   [x] Confirming I have added all sensitive information-related should be inside .env files

### Client:

-   [x] **Console :** Confirming no console errors in the UI for this update.

-   [x] **Import order :** Confirming correct import order.

```
# External Import
import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { useDispatch, useSelector, shallowEqual } from 'react-redux';

# Internal Import
import { } from '../../Api/ApiRoutes';
import { } from '../../constants/AppConstant';
```

-   [x] **Re-renders :** Confirming minimal re-renders for new React components.

-   [x] **Network calls :** Confirming efficient network/API calls, minimized as needed.

-   [x] **Util function comments :** Confirming comprehensive comments for utility functions.

-   [x] **Image optimization :** Confirming I have checked that all images are optimized. If not, please use https://tinyjpg.com/ or https://vecta.io/nano.

-   [x] **Dead code :** Confirming I have removed all comments code which is of no use OR written why I have kept the commented code.

### Confirming different viewport testing of the entire flow:

-   [x] Tested on 280px viewport
-   [x] Tested on 320px viewport
-   [x] Tested on 375px viewport
-   [x] Tested on 425px viewport
-   [x] Tested on 768px viewport
-   [x] Tested on 1024px viewport
-   [x] Tested on 1440px viewport
-   [x] Tested on 2560px viewport

### End-to-end testing:

-   [x] **Happy flow :** Successfully tested end-to-end happy flow, all working as expected.
-   [ ] **Error flow :** Tested UI flow with error scenarios, gracefully handled errors on UI
-   [ ] **Common component changed :** Tested change in common component across views to prevent breaking elsewhere.

2024-02-28 10:49 UTC, ram-primathon requested changes

2024-02-28 10:49 UTC, ram-primathon commented on src/assets/images/index.js
move this index file inside assets folder

2024-02-28 10:49 UTC, ram-primathon commented on src/assets/images/index.js
> +export { default as ourServiceImage1} from "/src/assets/images/our-service-1.png"
make it a relative import

2024-02-28 10:49 UTC, ram-primathon commented on src/assets/images/index.js
> +export { default as ourServiceImage2} from "/src/assets/images/our-service-2.png"
```suggestion
export { default as ourServiceImage2} from "./homepage/our-service-2.png"
```

2024-02-28 11:02 UTC, ram-primathon requested changes

2024-02-28 11:02 UTC, ram-primathon commented on src/assets/images/our-service-1.png
move this to homepage folder

2024-02-28 11:49 UTC, Himanshushakyaa commented on src/assets/images/our-service-1.png
sir iye smjh nhi ayaa

2024-02-29 05:34 UTC, ram-primathon approved these changes

2024-02-29 05:34 UTC, merged

2024-02-29 05:35 UTC, ram-primathon commented
Good Job 👍. Thank you.