[Feature] : Our services section enhancement
primathonacademy/april-batch-live-project pull request #46
Opened 2024-03-13 07:19 UTC by SahilVermaFED

## Description

-   [Ticket Link]
-  our services section fully responsive with scrolling and line background design

## UI screenshot or Video

-   Please include a screenshot or video to help reviewers understand the specific part of the application being modified. Multiple screenshots are appreciated

---

## Checklist - All needs to be ticked before sending PR for review:

### General:

-   [x] **PR Size :** Confirming PR size < 20 files or pre-approved if > 20 files.
-   [x] **Self Review :** Confirming I have self-reviewed my PR
-   [x] **Peers Review :** - [ ] @Dev 1
-   [x] Confirming I have added all sensitive information-related should be inside .env files

### Client:

-   [x] **Console :** Confirming no console errors in the UI for this update.
-   [x] **Import order :** Confirming correct import order.

```
# External Import
import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { useDispatch, useSelector, shallowEqual } from 'react-redux';

# Internal Import
import { } from '../../Api/ApiRoutes';
import { } from '../../constants/AppConstant';
```

-   [x] **Re-renders :** Confirming minimal re-renders for new React components.

-   [x] **Network calls :** Confirming efficient network/API calls, minimized as needed.

-   [x] **Util function comments :** Confirming comprehensive comments for utility functions.

-   [x] **Image optimization :** Confirming I have checked that all images are optimized. If not, please use https://tinyjpg.com/ or https://vecta.io/nano.

-   [x] **Dead code :** Confirming I have removed all comments code which is of no use OR written why I have kept the commented code.

### Confirming different viewport testing of the entire flow:

-   [x] Tested on 280px viewport
-   [x] Tested on 320px viewport
-   [x] Tested on 375px viewport
-   [x] Tested on 425px viewport
-   [x] Tested on 768px viewport
-   [x] Tested on 1024px viewport
-   [x] Tested on 1440px viewport
-   [x] Tested on 2560px viewport
### End-to-end testing:

-   [x] **Happy flow :** Successfully tested end-to-end happy flow, all working as expected.
-   [x] **Error flow :** Tested UI flow with error scenarios, gracefully handled errors on UI
-   [x] **Common component changed :** Tested change in common component across views to prevent breaking elsewhere.

2024-03-13 11:54 UTC, ram-primathon requested changes

2024-03-13 11:54 UTC, ram-primathon commented on src/pages/homepage/OurServiceSection.jsx
> +    if (window.innerWidth >= SCREEN_SIZE.MD && window.innerWidth <= SCREEN_SIZE.LG) {
use css for this

2024-03-14 07:40 UTC, ram-primathon requested changes

2024-03-14 07:40 UTC, ram-primathon commented on src/pages/homepage/OurServiceSection.jsx
> +    if (window.innerWidth >= SCREEN_SIZE.MD && window.innerWidth <= SCREEN_SIZE.LG) {
display: -webkit-box;
-webkit-box-orient: vertical;
-webkit-line-clamp: 3;
overflow: hidden;

2024-03-14 07:40 UTC, ram-primathon commented on tailwind.config.js
> +    // eslint-disable-next-line no-undef
this should be the last choice

2024-03-14 10:18 UTC, SahilVermaFED commented on src/pages/homepage/OurServiceSection.jsx
> +    if (window.innerWidth >= SCREEN_SIZE.MD && window.innerWidth <= SCREEN_SIZE.LG) {
done Sir

2024-03-14 10:18 UTC, SahilVermaFED commented on tailwind.config.js
> +    // eslint-disable-next-line no-undef
done sir

2024-03-15 05:57 UTC, merged