[Feature] : Add improvement in explore section component
primathonacademy/april-batch-live-project pull request #53
Opened 2024-03-18 16:33 UTC by Himanshushakyaa

## Description

-   [Ticket Link](#) (if any)
-    Add UI design improvement in exlpore service section

## UI screenshot or Video

-   

https://github.com/primathonacademy/april-batch-live-project/assets/131392846/b28ca4f4-5e74-43eb-924b-94c7d98014ff

---

## Checklist - All needs to be ticked before sending PR for review:

### General:

-   [x] **PR Size :** Confirming PR size < 20 files or pre-approved if > 20 files.
-   [x] **Self Review :** Confirming I have self-reviewed my PR
-   [x] **Peers Review :** - [ ] @Dev 1
-   [x] Confirming I have added all sensitive information-related should be inside .env files

### Client:

-   [] **Console :** Confirming no console errors in the UI for this update.

-   [ ] **Import order :** Confirming correct import order.

```
# External Import
import React, { useState, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { useDispatch, useSelector, shallowEqual } from 'react-redux';

# Internal Import
import { } from '../../Api/ApiRoutes';
import { } from '../../constants/AppConstant';
```

-   [x] **Re-renders :** Confirming minimal re-renders for new React components.

-   [x] **Network calls :** Confirming efficient network/API calls, minimized as needed.

-   [x] **Util function comments :** Confirming comprehensive comments for utility functions.

-   [] **Image optimization :** Confirming I have checked that all images are optimized. If not, please use https://tinyjpg.com/ or https://vecta.io/nano.

-   [ ] **Dead code :** Confirming I have removed all comments code which is of no use OR written why I have kept the commented code.

### Confirming different viewport testing of the entire flow:

-   [x] Tested on 280px viewport
-   [x] Tested on 320px viewport
-   [x] Tested on 375px viewport
-   [x] Tested on 425px viewport
-   [x] Tested on 768px viewport
-   [x] Tested on 1024px viewport
-   [x] Tested on 1440px viewport
-   [x] Tested on 2560px viewport

### End-to-end testing:

-   [x] **Happy flow :** Successfully tested end-to-end happy flow, all working as expected.
-   [ ] **Error flow :** Tested UI flow with error scenarios, gracefully handled errors on UI
-   [ ] **Common component changed :** Tested change in common component across views to prevent breaking elsewhere.

2024-03-19 06:39 UTC, ram-primathon requested changes

2024-03-19 06:39 UTC, ram-primathon commented on src/assets/images/our-service-1.jpg
Why have you used jpg and not png? have you used tinypng to compress this image?

2024-03-19 08:23 UTC, Himanshushakyaa commented on src/assets/images/our-service-1.jpg
sir i use image after tinify but png image not  show clearly , background passing in this so i have used jpg

2024-03-20 05:03 UTC, ram-primathon commented on src/assets/images/our-service-1.jpg
Please use png only

2024-03-21 04:37 UTC, closed without merging